### ISSUE TITLE
LoadError: Cannot load such file -- ./app/models/marc_indexer

### ISSUE THREAD

**Issue by arpithparikh** [projectblacklight/blacklight-marc#36]
rake solr:marc:index MARC_FILE= /var/www/project1/my_new_blacklightapp/1.mrc
rake aborted!
LoadError: cannot load such file -- ./app/models/marc_indexer

Tasks: TOP => solr:marc:index => solr:marc:index:work
(See full trace by running task with --trace)

**Comment by barmintor** [comment]
Need more information to reproduce; this issue may be too stale to keep open. Is this after running the install generator?
