### ISSUE TITLE
Fix "Librarian View" display

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/blacklight-marc#43]
- [ ] use a fixed-width font
- [ ] legibly style tags 

<img width="523" alt="screen shot 2017-01-23 at 12 14 48 pm" src="https://cloud.githubusercontent.com/assets/111218/22220923/8faa0794-e165-11e6-8547-3513f6c28990.png">

**Comment by barmintor** [comment]
Related: https://github.com/projectblacklight/blacklight/issues/1580

**Comment by barmintor** [comment]
Monospace font, easy enough. Not sure where the background color on `div.tag` is coming from.
