### ISSUE TITLE
Librarian view does not work after quickstart in Rails 6

### ISSUE THREAD

**Issue by sandbergja** [projectblacklight/blacklight-marc#85]
Steps to recreate:
1. Create an application the hard way:
  - `rails new my_new_blacklightapp`
  - `cd my_new_blacklightapp`
  - Add blacklight to the Gemfile
  - `bundle install`
  - `gem install devise devise-guests`
  - `rails generate blacklight:install --devise --marc --solr_version=latest`
  - `rake db:migrate`
  - `bundle exec solr_wrapper`
  - `rake solr:marc:index_test_data`
  - `rails s`
2. Check app/models/solr_document.rb.  Note that the marc source field is called :marc_ss and it's in the marcxml format.
3. Open up solr, and look at the documents.  Notice that they all have marc_ss fields with marcxml data
4. Open up the show view of a record.  Note that the librarian view link does not appear.
5. Go to http://localhost:3000/catalog/2007020969/librarian_view.  Note that it says "No MARC data found."

I tried this with ruby 2.5.7 and jruby 9.2.9.0.  I'm on rails 6.0.2.1, so it could be a rails 6 issue?

**Comment by sandbergja** [comment]
Yep, this looks like it is totally a Rails 6 issue.  I followed these exact same steps on rails 5.4.2.1, and everything appeared as expected.

**Comment by cdmo** [comment]
Seeing the same problem after upgrading our catalog to Rails 6 (from 5.2). Haven't narrowed in on the exact cause yet.

**Comment by sandbergja** [comment]
Additional data point: when I add `config.autoloader = :classic` to config/application.rb, I can get the librarian view.

So... seems like it could be a zeitwerk issue?

**Comment by cdmo** [comment]
I've seen the same. When I have zeitwerk enabled I do see this in the logs for every initial load of librarian view:

```
NameError - uninitialized constant Blacklight::Solr::Document::Marc
Did you mean?  Blacklight::Marc:
  app/models/solr_document.rb:29:in `<class:SolrDocument>'
  app/models/solr_document.rb:3:in `<top (required)>'
```

`solr_document.rb`:

```rb
  # The following shows how to setup this blacklight document to display marc documents
  use_extension(Blacklight::Solr::Document::Marc) do |document|
    document.key?(:marc_display_ss)
  end
```

Weirdly it seems like Rails can't find this despite the fact that it appears to be in the right place. It is at `app/models/concerns/blacklight/solr/document/marc.rb` and the name of the module matches and should be autoloaded in.

Further down in my solr_document.rb I have `use_extension(Blacklight::Document::DublinCore)
` and this works just fine (it is found at `blacklight-7.5.0/app/models/concerns/blacklight/document/dublin_core.rb`). 

Something unique to blacklight marc seems to be breaking zeitwerk? Not sure yet.

**Comment by cdmo** [comment]
Kinda wonder if it has to do with the fact that project blacklight defines the namespace `Blacklight::Solr::Document` in `lib` while blacklight marc puts it in `app/models/concern` - perhaps there is a race going on and blacklight's definition of the namespace living in `lib` arrives first and wins and then it can't find things in app/models/concern in that same namespace. As in Rails just thinks `Blacklight::Solr::Document` must live at a `lib` sub directory? Doesn't make a lot of sense I'll admit.

However, I renamed the two modules (`Blacklight::Solr::Document::Marc` and `Blacklight::Solr::Document::MarcExport`) and placed them at `app/models/concerns` in my application then changed calls in `solr_document.rb` to these two. No `NameError`s violations and the marc rendered fine (well if you can call flat marc "fine")

**Comment by cdmo** [comment]
Looks like maybe my hunch is right? See the "Rules of thumb" (exact language of the projects `README.md` fwiw) at https://github.com/fxn/zeitwerk#rules-of-thumb

> if two loaders manage files that translate to the same constant in the same namespace, the first one wins, the rest are ignored.

So, if I'm reading this correctly, it sounds like we need to either move the `Blacklight::Solr::Document::Marc` and `Blacklight::Solr::Document::MarcExport` into `app/models/concerns` or just manually load the dependency first (i.e., "Projects that reopen a namespace defined by some dependency have to ensure said namespace is loaded before setup. That is, the project has to make sure it reopens, rather than define. This is often accomplished just loading the dependency."). I'll look into it some more.

**Comment by sandbergja** [comment]
I'm not seeing this issue anymore, so I will close it. :-)
